#pragma once

#include "common.h"

#define TILE_SIZE 32
#define PLAYER_SIZE 64
#define ANIMATION_SPEED .3f

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720

#define MAX_BULLETS 100
#define BULLET_LIFTIME 1.f
#define BULLET_SPEED 15.f

#define ASTEROID_SPAWN_RATE 1.f
#define MAX_ASTEROIDS 64
#define ASTEROID_SPAWN_LIMIT 3

#define ASTEROID_SPEED_MIN 50.0f
#define ASTEROID_SPEED_MAX 150.0f
#define BOSS_SCORE_THRESHOLD_PONG 1500

#define BALL_SPEED_INITIAL 400.0f
#define BALL_SPEED_MAX 600.0f
#define PADDLE_MOVE_SPEED 450.0f
#define PADDLE_AI_REACTION_DELAY 0.0f

#define MAX_BRICKS 4

// Split animation timing
#define SPLIT_DURATION_SHAKE 1.8f
#define SPLIT_DURATION_ROTATE 0.5f
#define SPLIT_DURATION_EXIT 0.5f
#define SPLIT_DURATION_WARN 1.5f
#define SPLIT_DURATION_ENTRY 1.f

#define BRICK_WIDTH (TILE_SIZE * 8)
#define BRICK_HEIGHT (TILE_SIZE * 2)

#define BRICK_SPEED 3.f
#define BRICK_MAX_PROJECTILES 100
#define BRICK_PROJECTILE_SPEED 8.f

#define BRICK_SPACING_X TILE_SIZE * 4
#define BRICK_SPACING_Y TILE_SIZE * 4
#define BRICK_FORMATION_Y 0
